/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Exercise = {
  type?: "exercise";
  exerType: string;
  instructions: {
    content: string;
    [k: string]: unknown;
  };
  content: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
} & (ReviewResponse | ReviewResponse1);

export interface EvaluateTaskResponse {
  data: {
    task: {
      name: string;
      display?: "vertical" | "horizontal";
      description: string;
      entries: (Group | Exercise)[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Group {
  type?: "group";
  resources: {
    content: string;
    [k: string]: unknown;
  }[];
  entries: (Exercise | Group)[];
  [k: string]: unknown;
}
export interface ReviewResponse {
  exerType: "Doplnovacka";
  content: (Cmb | TxtI | string)[];
  [k: string]: unknown;
}
export interface Cmb {
  userValue: string;
  correctValue?: string;
  [k: string]: unknown;
}
export interface TxtI {
  value?: string;
  [k: string]: unknown;
}
export interface ReviewResponse1 {
  exerType: "HledaniChyb";
  content: {
    userText: string;
    correctText?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
