/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Specifies format of the request body.
 */
export interface Request {
  data: RequestData;
}
/**
 * Endpoint specific request data.
 */
export interface RequestData {
  [k: string]: unknown;
}
