/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Specifies format of successfull response.
 */
export interface ApplicationSuccessResponse {
  data: ResponseData;
  [k: string]: unknown;
}
/**
 * Specifies endpoint and request specific response data
 */
export interface ResponseData {
  [k: string]: unknown;
}
