/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Human readable error message
 */
export type HumanReadableErrorMessage = string;
/**
 * Serves as identifier for action which should be triggered by app.
 */
export type EndpointSpecificErrorCode = number;
/**
 * Serves as error action specific data.
 */
export type ErrorData =
  | {
      [k: string]: unknown;
    }
  | unknown[];
/**
 * Human readable details about error or help message, specifying which action should user take
 */
export type HumanReadableErrorDescription = string;

/**
 * Serves as object specifying details about the error for both application and user.
 */
export interface ApplicationErrorObject {
  message: HumanReadableErrorMessage;
  code: EndpointSpecificErrorCode;
  errorData?: ErrorData;
  description: HumanReadableErrorDescription;
  [k: string]: unknown;
}
