/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Value = string;

export interface ReviewResponse {
  exerType: "Doplnovacka";
  content: (Cmb | TxtI | Value)[];
  [k: string]: unknown;
}
export interface Cmb {
  userValue: string;
  correctValue?: string;
  [k: string]: unknown;
}
export interface TxtI {
  value?: string;
  [k: string]: unknown;
}
