/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Value = string;

export interface TakeResponse {
  exerType: "Doplnovacka";
  content: (Cmb | TxtI | Value)[];
  [k: string]: unknown;
}
export interface Cmb {
  /**
   * @minItems 1
   */
  values: [
    {
      [k: string]: unknown;
    },
    ...{
      [k: string]: unknown;
    }[]
  ];
  selectedIndex?: number | null;
  [k: string]: unknown;
}
export interface TxtI {
  value?: string | null;
  [k: string]: unknown;
}
