/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SaveTaskSuccessfulRequest {
  data: {
    exercises: (DoplnovackaSaveRequest | HledaniChybSaveRequest)[];
  };
  [k: string]: unknown;
}
export interface DoplnovackaSaveRequest {
  /**
   * @minItems 1
   */
  content?: [number | string, ...(number | string)[]];
  [k: string]: unknown;
}
export interface HledaniChybSaveRequest {
  content?: string;
  [k: string]: unknown;
}
